on: push


name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          #args: --release --all-features
      - name: tests
        run: |
          for i in tests/fasten_*.sh; do echo $i; echo ===; bash $i; echo; done;

